### ISSUE TITLE
Order gets created when refreshing the page at CC/DC form page

### ISSUE THREAD

**Issue by stevenobird** [heidelpay/magento-cd-edition#12]
When doing the described behaviour at the creditcard/debitcard checkout page, the order gets created, but no transaction will be created on the heidelpay side.

**Comment by heidelpay** [comment]
This is a feature not a bug. :-) The reason for this is a double pay prevention. If you have paid successful and hit back on the success page. This prevents you from getting a new credit card payment frame. 

The problem is extension can not dissed between reload and back. But if it is a reload you will go to the success page but the order is not been market as paid.
